apiVersion: v1
kind: Service
metadata:
  name: pipeline-example-backend-stg
  labels:
    app: pipeline-example-backend-stg
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: pipeline-example-backend-stg
  sessionAffinity: None
